[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Brains Cogs"
authors = [{name = "Brains", email = "jscarfo@purdue.edu"}]
dynamic = ["version", "description"]